### ISSUE TITLE
HtmlHelper::image() is not exist on API doc from 2.0 to 2.7

### ISSUE THREAD

**Issue by kanonji** [cakephp/cakephp-api-docs#85] opened 2017-03-16 05:09 UTC
I find that `HtmlHelper::image()` is not exist on API doc from `2.0` to `2.7` when I maintain bit old website based on CakePHP `2.5`.

https://api.cakephp.org/2.7/class-HtmlHelper.html#_image
https://api.cakephp.org/2.6/class-HtmlHelper.html#_image
https://api.cakephp.org/2.5/class-HtmlHelper.html#_image
https://api.cakephp.org/2.4/class-HtmlHelper.html#_image
https://api.cakephp.org/2.3/class-HtmlHelper.html#_image
https://api.cakephp.org/2.2/class-HtmlHelper.html#_image
https://api.cakephp.org/2.1/class-HtmlHelper.html#_image
https://api.cakephp.org/2.0/class-HtmlHelper.html#_image

## Exists from 2.8

https://api.cakephp.org/2.8/class-HtmlHelper.html#_image

**Comment by antograssiot** [comment] 2017-03-16 05:20
There are a lot of function missing, not only images.
The root cause is the unescaped '<' tag in https://api.cakephp.org/2.5/source-class-HtmlHelper.html#410
It has been fixed in 2.8 as you mentioned so you can either use this, or look into the docblock as this is from where the API is generated.
I dont think patching those version make sense.

**Comment by markstory** [comment] 2017-03-16 15:18
>  I dont think patching those version make sense.

Agreed. The most recent API docs are fixed, and I don't really have the time/interest/energy to fix all the old releases.

**Closed by markstory** 2017-03-16 15:18 UTC
